-- AlterTable
ALTER TABLE `settings` ADD COLUMN `freeTravelKm` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `maxServiceKm` DOUBLE NOT NULL DEFAULT 50,
    ADD COLUMN `travelRatePerKm` DOUBLE NOT NULL DEFAULT 10;
